### ISSUE TITLE
bigint-to-jsbi?

### ISSUE THREAD

**Issue by mimoo** [GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint#9]
Is there such a plugin :) ?

Thanks!

**Comment by mathiasbynens** [comment]
Building such a plugin is not feasible, for the reasons explained here: https://github.com/GoogleChromeLabs/jsbi#why

**Comment by Yaffle** [comment]
https://github.com/Yaffle/babel-plugin-transform-bigint
It is buggy right now (!). ideally, it should try to analyze operand types statically to detect if an operator should be replaced with JSBI method call, or just skipped, or replaced with a function which will do type checking.
Just use the plugin against a limited part of your code to avoid "performance penalties".
